### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by vabatta** [samueldeng/alfred-keepass#8]
Hi,

first of all great job! Just moved into Alfred and this was my first workflow I wanted to import. Then I got inspired and I made few code changes to add a bit of functionality.
Available at my forked repo [here](https://github.com/vabatta/alfred-keepass/tree/master).

@samueldeng If you want, I can make a pull request to merge it, as you wish.

**Comment by zeltak** [comment]
@vabatta This is Epic

thx so much for your fork it worked so great! are you going to continue development?
There is no place to add "issues" in your fork?
for example, would be great to have an option to "launch" in macpass to open the entry in macpass

thx again!

Z
